version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t jaysun94/docker-travis -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: docker run -e CI=true jaysun94/docker-travis npm run test -- --coverage
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Configure AWS Credentials
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Upload to Elastic Beanstalk
          command: |
            aws s3 cp Dockerrun.aws.json s3://$S3_BUCKET_NAME/Dockerrun.aws.json --region $AWS_DEFAULT_REGION
            aws elasticbeanstalk create-application-version --application-name $EB_APP_NAME --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=Dockerrun.aws.json --region $AWS_DEFAULT_REGION
            aws elasticbeanstalk update-environment --environment-name $EB_ENV_NAME --version-label $CIRCLE_SHA1 --region $AWS_DEFAULT_REGION

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
