version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t jaysun94/docker-travis -f Dockerfile.dev .
      - run:
          name: Run Tests
          command: docker run -e CI=true jaysun94/docker-travis npm run test -- --coverage
workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
